"""Migration

Revision ID: 8059985beed1
Revises: d86b14989681
Create Date: 2020-12-07 18:07:55.435065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8059985beed1'
down_revision = 'd86b14989681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
